FROM ubuntu

RUN apt-get -y update 
RUN apt-get -y install openjdk-8-jdk wget
RUN mkdir /usr/local/tomcat
RUN wget http://apachemirror.wuchna.com/tomcat/tomcat-8/v8.5.53/bin/apache-tomcat-8.5.53.tar.gz -O /tmp/tomcat.tar.gz
RUN cd /tmp&& tar xvfz tomcat.tar.gz
RUN cp -Rv /tmp/apache-tomcat-8.5.53/* /usr/local/tomcat/

COPY sampleapp.war /usr/local/tomcat/webapps/

EXPOSE 8080
CMD /usr/local/tomcat/bin/catalina.sh run
