apiVersion: v1
kind: Namespace
metadata:
  name: demo-metrics
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-example-app
  namespace: demo-metrics
  labels:
    app: prometheus-example-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prometheus-example-app
  template:
    metadata:
      labels:
        app: prometheus-example-app
    spec:
      containers:
        - name: app
          image: quay.io/brancz/prometheus-example-app:v0.5.0
          ports:
            - name: http
              containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus-example-app
  namespace: demo-metrics
  labels:
    app: prometheus-example-app
spec:
  selector:
    app: prometheus-example-app
  ports:
    - name: http
      port: 8080
      targetPort: http
