apiVersion: v1
kind: Pod
metadata:
  name: pod-gitrepo-vol
  labels:
    app: myapp
spec:
  containers:
   - name: web
     image: nginx:alpine
     ports:
      - protocol: TCP
        containerPort: 80
     volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html/
        readOnly: true
  volumes:
    - name: html
      gitRepo:
        repository: https://github.com/lerndevops/nginx.git
        revision: master
        directory: .
