apiVersion: v1
kind: Pod
metadata:
  name: nginx
  labels:
     tier: frontend
spec:
  containers:
   - name: nginx
     image: nginx
     ports:
      - containerPort: 80
     volumeMounts:
       - name: nginx-vol
         mountPath: /usr/share/nginx/html/
  volumes:
   - name: nginx-vol
     emptyDir: {}
	 