apiVersion: v1
kind: Pod
metadata:
   name: mypod
   labels:
     app: myapp
spec:
   containers:
     - name: httpd
       image: httpd
       #       ports:
       #  - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: mysvc
spec:
  type: ClusterIP 
  selector:
    app: myapp
  ports:
   - protocol: TCP
     port: 80
